# Generated by Django 3.2.7 on 2021-10-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_rename_domanin_url_client_domain_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='domain_url',
        ),
        migrations.AddField(
            model_name='client',
            name='domain',
            field=models.CharField(default='', max_length=50),
        ),
    ]
